services:
  webapp:
    container_name: webapp-mateo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./media-data:/app/publish/wwwroot/media
      - ./albums-data:/app/publish/wwwroot/albums
