services:
  webapp:
    container_name: webapp-mateo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ~/.media/songs:/app/wwwroot/media
      - ~/.media/albums:/app/wwwroot/albums