services:
  webapp:
    container_name: webapp-mateo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - media-data:/app/wwwroot/media
      - albums-data:/app/wwwroot/albums

volumes:
  media-data:
  albums-data: