services:
  webapp:
    container_name: PersonalCloud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ~/Desktop/cloud-data:/app/publish/wwwroot/media
      - ~/Desktop/cloud-albums:/app/publish/wwwroot/albums