services:
  webapp:
    container_name: webapp-mateo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ~/Desktop/cloud-data/media:/app/publish/wwwroot/media
      - ~/Desktop/cloud-data/albums:/app/publish/wwwroot/albums