name: Deployment Pipeline
on : 
    push:
      branches:
       - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 # git clone

      - name: Docker compose down
        run: docker compose down --remove-orphans

      - name: Docker compose up
        run: docker compose up -d --build
