name: Deployment Pipeline
on : 
- push
- workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 # git clone

      - name: Docker compose pull
        run: docker-compose pull
      - name: Docker compose down
        run: docker-compose down

      - name: Docker compose up
        run: docker-compose up -d --build
